language: python
dist: bionic
python:
  - "3.11"
before_install:
  # - source ~/eb-virt/python3.11/bin/activate
  - pip install 'urllib3<2.0'
  - sudo apt-get update
  - sudo apt-get install -y sqlite3 libsqlite3-dev
  # Verify SQLite version
  - sqlite3 --version
  # - pip freeze > requirements.txt
install:
  - pip install -r requirements.txt

before_script:
  # - source ~/virtualenv/python3.11/bin/activate
  # - pip install -r requirements.txt
  - python manage.py migrate
  - python manage.py collectstatic --noinput
before_deploy: "echo 'ready?'"

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "mysite"
  env: "mysite-dev2"
  bucket_name: "$S3_BUCKET_NAME"

script:
  # Check code formatting with black.
  - black --check .
  # Run flake8 linter.
  - flake8 .
  # Run your test suite and capture coverage.
  - coverage run --source=polls manage.py test

after_script:
# Report coverage to coveralls.
  - coveralls
