language: python
python:
  - "3.9"
before_install:
  - source ~/eb-virt/bin/activate
# command to install dependencies
install:
  - pip install -r requirements.txt>
# command to run tests
# Set max line length for flake8 to 88 to match black.

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput
before_deploy: "echo 'ready?'"

after_deploy:
  - ./after_deploy_1.sh
  - ./after_deploy_2.sh
  
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIASDF6ZWVYUF6ULQPF"
  secret_access_key:
    secure: "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"
  region: "us-east-1"
  app: "mysite"
  env: "mysite-dev"
  bucket_name: "the-target-S3-bucket"
  on:
    branch: master # Or whichever branch you want to deploy from.

script:
  # Check code formatting with black.
  - black --check .
  # Run flake8 linter.
  - flake8 --max-line-length=91
  # Run your test suite and capture coverage.
  - coverage run --source=polls manage.py test


after_script:
# Report coverage to coveralls.
  - coveralls

# Only run Travis CI on master branch.
branches:
  only:
    - master